server:
  port: 8085

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_split

redis:
  host: localhost
  port: 6379
  password: ""

auth_client:
  host: localhost
  port: 8084
  update_interval: 60

file_service:
  base_url: http://localhost:8082
  service_id: 3

id_service:
  base_url: http://localhost:8083
  service_id: 2

tvm:
  base_url: http://localhost:8081
  service_id: 4
  service_secret: "DXRZ2QMo9YKvspsua8FifxToEUFyQ5pyXqfIA49vOaB4QxvNb4MPnQjTfiSg30NctFcbVzyWW1tA6PwtZr35xw=="

migrations:
  path: migrations

logger:
  level: info 