server:
  port: ":8082"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "ff_files"

storage:
  base_path: "/app/storage"
  max_file_size: 10485760  # 10MB
  allowed_mime_types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "text/plain"
  temp_url_expiration: "24h"
  soft_delete_timeout: "720h"  # 30 days

tvm:
  url: "http://ff-tvm:8083" 