server:
  port: ":8082"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "ff_files"

storage:
  basePath: "./storage"
  maxFileSize: 10485760  # 10MB
  allowedMimeTypes:
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "application/pdf"
    - "text/plain"
  tempURLExpiration: "24h"
  softDeleteTimeout: "720h"  # 30 days 