version: '3'

services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=ff-files
      - MINIO_INTERNAL_ENDPOINT=http://minio:9000
      - TVM_BASE_URL=http://host.docker.internal:8081
      - TVM_SERVICE_ID=3
    networks:
      - shared_network
    depends_on:
      minio:
        condition: service_healthy

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 10s
      retries: 6
    networks:
      - shared_network

networks:
  shared_network:
    external: true

volumes:
  minio_data: