// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/login_history.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/ivasnev/FinFlow/ff-auth/internal/service"
)

// MockLoginHistory is a mock of LoginHistory interface.
type MockLoginHistory struct {
	ctrl     *gomock.Controller
	recorder *MockLoginHistoryMockRecorder
}

// MockLoginHistoryMockRecorder is the mock recorder for MockLoginHistory.
type MockLoginHistoryMockRecorder struct {
	mock *MockLoginHistory
}

// NewMockLoginHistory creates a new mock instance.
func NewMockLoginHistory(ctrl *gomock.Controller) *MockLoginHistory {
	mock := &MockLoginHistory{ctrl: ctrl}
	mock.recorder = &MockLoginHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginHistory) EXPECT() *MockLoginHistoryMockRecorder {
	return m.recorder
}

// GetUserLoginHistory mocks base method.
func (m *MockLoginHistory) GetUserLoginHistory(ctx context.Context, userID int64, limit, offset int) ([]service.LoginHistoryParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLoginHistory", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]service.LoginHistoryParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLoginHistory indicates an expected call of GetUserLoginHistory.
func (mr *MockLoginHistoryMockRecorder) GetUserLoginHistory(ctx, userID, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLoginHistory", reflect.TypeOf((*MockLoginHistory)(nil).GetUserLoginHistory), ctx, userID, limit, offset)
}
