// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/category.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/ivasnev/FinFlow/ff-split/internal/service"
)

// MockCategory is a mock of Category interface.
type MockCategory struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryMockRecorder
}

// MockCategoryMockRecorder is the mock recorder for MockCategory.
type MockCategoryMockRecorder struct {
	mock *MockCategory
}

// NewMockCategory creates a new mock instance.
func NewMockCategory(ctrl *gomock.Controller) *MockCategory {
	mock := &MockCategory{ctrl: ctrl}
	mock.recorder = &MockCategoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategory) EXPECT() *MockCategoryMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockCategory) CreateCategory(ctx context.Context, category *service.CategoryDTO, categoryType string) (*service.CategoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", ctx, category, categoryType)
	ret0, _ := ret[0].(*service.CategoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockCategoryMockRecorder) CreateCategory(ctx, category, categoryType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockCategory)(nil).CreateCategory), ctx, category, categoryType)
}

// DeleteCategory mocks base method.
func (m *MockCategory) DeleteCategory(ctx context.Context, id int, categoryType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCategory", ctx, id, categoryType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCategory indicates an expected call of DeleteCategory.
func (mr *MockCategoryMockRecorder) DeleteCategory(ctx, id, categoryType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCategory", reflect.TypeOf((*MockCategory)(nil).DeleteCategory), ctx, id, categoryType)
}

// GetCategories mocks base method.
func (m *MockCategory) GetCategories(ctx context.Context, categoryType string) ([]service.CategoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx, categoryType)
	ret0, _ := ret[0].([]service.CategoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockCategoryMockRecorder) GetCategories(ctx, categoryType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockCategory)(nil).GetCategories), ctx, categoryType)
}

// GetCategoryByID mocks base method.
func (m *MockCategory) GetCategoryByID(ctx context.Context, id int, categoryType string) (*service.CategoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryByID", ctx, id, categoryType)
	ret0, _ := ret[0].(*service.CategoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryByID indicates an expected call of GetCategoryByID.
func (mr *MockCategoryMockRecorder) GetCategoryByID(ctx, id, categoryType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryByID", reflect.TypeOf((*MockCategory)(nil).GetCategoryByID), ctx, id, categoryType)
}

// GetCategoryTypes mocks base method.
func (m *MockCategory) GetCategoryTypes() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategoryTypes")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategoryTypes indicates an expected call of GetCategoryTypes.
func (mr *MockCategoryMockRecorder) GetCategoryTypes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategoryTypes", reflect.TypeOf((*MockCategory)(nil).GetCategoryTypes))
}

// UpdateCategory mocks base method.
func (m *MockCategory) UpdateCategory(ctx context.Context, id int, category *service.CategoryDTO, categoryType string) (*service.CategoryDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCategory", ctx, id, category, categoryType)
	ret0, _ := ret[0].(*service.CategoryDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCategory indicates an expected call of UpdateCategory.
func (mr *MockCategoryMockRecorder) UpdateCategory(ctx, id, category, categoryType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCategory", reflect.TypeOf((*MockCategory)(nil).UpdateCategory), ctx, id, category, categoryType)
}
