// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ivasnev/FinFlow/ff-split/internal/models"
	service "github.com/ivasnev/FinFlow/ff-split/internal/service"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AddUsersToEvent mocks base method.
func (m *MockUser) AddUsersToEvent(ctx context.Context, ids []int64, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToEvent", ctx, ids, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsersToEvent indicates an expected call of AddUsersToEvent.
func (mr *MockUserMockRecorder) AddUsersToEvent(ctx, ids, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToEvent", reflect.TypeOf((*MockUser)(nil).AddUsersToEvent), ctx, ids, eventID)
}

// BatchCreateDummyUsers mocks base method.
func (m *MockUser) BatchCreateDummyUsers(ctx context.Context, names []string, eventID int64) ([]*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateDummyUsers", ctx, names, eventID)
	ret0, _ := ret[0].([]*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchCreateDummyUsers indicates an expected call of BatchCreateDummyUsers.
func (mr *MockUserMockRecorder) BatchCreateDummyUsers(ctx, names, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateDummyUsers", reflect.TypeOf((*MockUser)(nil).BatchCreateDummyUsers), ctx, names, eventID)
}

// BatchSyncUsersWithIDService mocks base method.
func (m *MockUser) BatchSyncUsersWithIDService(ctx context.Context, userIDs []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchSyncUsersWithIDService", ctx, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchSyncUsersWithIDService indicates an expected call of BatchSyncUsersWithIDService.
func (mr *MockUserMockRecorder) BatchSyncUsersWithIDService(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchSyncUsersWithIDService", reflect.TypeOf((*MockUser)(nil).BatchSyncUsersWithIDService), ctx, userIDs)
}

// CreateDummyUser mocks base method.
func (m *MockUser) CreateDummyUser(ctx context.Context, name string, eventID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDummyUser", ctx, name, eventID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDummyUser indicates an expected call of CreateDummyUser.
func (mr *MockUserMockRecorder) CreateDummyUser(ctx, name, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDummyUser", reflect.TypeOf((*MockUser)(nil).CreateDummyUser), ctx, name, eventID)
}

// CreateUser mocks base method.
func (m *MockUser) CreateUser(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUser)(nil).CreateUser), ctx, user)
}

// DeleteUser mocks base method.
func (m *MockUser) DeleteUser(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUserMockRecorder) DeleteUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUser)(nil).DeleteUser), ctx, id)
}

// GetDummiesByEventID mocks base method.
func (m *MockUser) GetDummiesByEventID(ctx context.Context, eventID int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDummiesByEventID", ctx, eventID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDummiesByEventID indicates an expected call of GetDummiesByEventID.
func (mr *MockUserMockRecorder) GetDummiesByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDummiesByEventID", reflect.TypeOf((*MockUser)(nil).GetDummiesByEventID), ctx, eventID)
}

// GetInternalUserIdsByExternalUserIds mocks base method.
func (m *MockUser) GetInternalUserIdsByExternalUserIds(ctx context.Context, externalUserIds []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInternalUserIdsByExternalUserIds", ctx, externalUserIds)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInternalUserIdsByExternalUserIds indicates an expected call of GetInternalUserIdsByExternalUserIds.
func (mr *MockUserMockRecorder) GetInternalUserIdsByExternalUserIds(ctx, externalUserIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInternalUserIdsByExternalUserIds", reflect.TypeOf((*MockUser)(nil).GetInternalUserIdsByExternalUserIds), ctx, externalUserIds)
}

// GetNotExistsUsers mocks base method.
func (m *MockUser) GetNotExistsUsers(ctx context.Context, ids []int64) ([]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotExistsUsers", ctx, ids)
	ret0, _ := ret[0].([]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotExistsUsers indicates an expected call of GetNotExistsUsers.
func (mr *MockUserMockRecorder) GetNotExistsUsers(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotExistsUsers", reflect.TypeOf((*MockUser)(nil).GetNotExistsUsers), ctx, ids)
}

// GetUserByExternalUserID mocks base method.
func (m *MockUser) GetUserByExternalUserID(ctx context.Context, userID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByExternalUserID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByExternalUserID indicates an expected call of GetUserByExternalUserID.
func (mr *MockUserMockRecorder) GetUserByExternalUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByExternalUserID", reflect.TypeOf((*MockUser)(nil).GetUserByExternalUserID), ctx, userID)
}

// GetUserByInternalUserID mocks base method.
func (m *MockUser) GetUserByInternalUserID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByInternalUserID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByInternalUserID indicates an expected call of GetUserByInternalUserID.
func (mr *MockUserMockRecorder) GetUserByInternalUserID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByInternalUserID", reflect.TypeOf((*MockUser)(nil).GetUserByInternalUserID), ctx, id)
}

// GetUsersByEventID mocks base method.
func (m *MockUser) GetUsersByEventID(ctx context.Context, eventID int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByEventID", ctx, eventID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByEventID indicates an expected call of GetUsersByEventID.
func (mr *MockUserMockRecorder) GetUsersByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByEventID", reflect.TypeOf((*MockUser)(nil).GetUsersByEventID), ctx, eventID)
}

// GetUsersByExternalIDs mocks base method.
func (m *MockUser) GetUsersByExternalIDs(ctx context.Context, externalIDs []int64) ([]service.ExternalToInternalMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByExternalIDs", ctx, externalIDs)
	ret0, _ := ret[0].([]service.ExternalToInternalMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByExternalIDs indicates an expected call of GetUsersByExternalIDs.
func (mr *MockUserMockRecorder) GetUsersByExternalIDs(ctx, externalIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByExternalIDs", reflect.TypeOf((*MockUser)(nil).GetUsersByExternalIDs), ctx, externalIDs)
}

// GetUsersByExternalUserIDs mocks base method.
func (m *MockUser) GetUsersByExternalUserIDs(ctx context.Context, userIDs []int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByExternalUserIDs", ctx, userIDs)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByExternalUserIDs indicates an expected call of GetUsersByExternalUserIDs.
func (mr *MockUserMockRecorder) GetUsersByExternalUserIDs(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByExternalUserIDs", reflect.TypeOf((*MockUser)(nil).GetUsersByExternalUserIDs), ctx, userIDs)
}

// GetUsersByInternalUserIDs mocks base method.
func (m *MockUser) GetUsersByInternalUserIDs(ctx context.Context, userIDs []int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByInternalUserIDs", ctx, userIDs)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByInternalUserIDs indicates an expected call of GetUsersByInternalUserIDs.
func (mr *MockUserMockRecorder) GetUsersByInternalUserIDs(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByInternalUserIDs", reflect.TypeOf((*MockUser)(nil).GetUsersByInternalUserIDs), ctx, userIDs)
}

// RemoveUserFromEvent mocks base method.
func (m *MockUser) RemoveUserFromEvent(ctx context.Context, userID, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromEvent indicates an expected call of RemoveUserFromEvent.
func (mr *MockUserMockRecorder) RemoveUserFromEvent(ctx, userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromEvent", reflect.TypeOf((*MockUser)(nil).RemoveUserFromEvent), ctx, userID, eventID)
}

// SyncUserWithIDService mocks base method.
func (m *MockUser) SyncUserWithIDService(ctx context.Context, userID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SyncUserWithIDService", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SyncUserWithIDService indicates an expected call of SyncUserWithIDService.
func (mr *MockUserMockRecorder) SyncUserWithIDService(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SyncUserWithIDService", reflect.TypeOf((*MockUser)(nil).SyncUserWithIDService), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockUser) UpdateUser(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUser)(nil).UpdateUser), ctx, user)
}
