version: '3'

services:
  app:
    build: .
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - POSTGRES_HOST=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ff_auth
      - TVM_BASE_URL=http://host.docker.internal:8081
      - ID_BASE_URL=http://host.docker.internal:8083
    networks:
      - shared_network


networks:
  shared_network:
    external: true
