// Code generated by MockGen. DO NOT EDIT.
// Source: internal/adapters/ffid.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	adapters "github.com/ivasnev/FinFlow/ff-split/internal/adapters"
)

// MockIDAdapter is a mock of IDAdapter interface.
type MockIDAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockIDAdapterMockRecorder
}

// MockIDAdapterMockRecorder is the mock recorder for MockIDAdapter.
type MockIDAdapterMockRecorder struct {
	mock *MockIDAdapter
}

// NewMockIDAdapter creates a new mock instance.
func NewMockIDAdapter(ctrl *gomock.Controller) *MockIDAdapter {
	mock := &MockIDAdapter{ctrl: ctrl}
	mock.recorder = &MockIDAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDAdapter) EXPECT() *MockIDAdapterMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockIDAdapter) GetUserByID(ctx context.Context, userID int64) (*adapters.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*adapters.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockIDAdapterMockRecorder) GetUserByID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockIDAdapter)(nil).GetUserByID), ctx, userID)
}

// GetUsersByIDs mocks base method.
func (m *MockIDAdapter) GetUsersByIDs(ctx context.Context, userIDs []int64) ([]adapters.UserDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByIDs", ctx, userIDs)
	ret0, _ := ret[0].([]adapters.UserDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByIDs indicates an expected call of GetUsersByIDs.
func (mr *MockIDAdapterMockRecorder) GetUsersByIDs(ctx, userIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByIDs", reflect.TypeOf((*MockIDAdapter)(nil).GetUsersByIDs), ctx, userIDs)
}
