server:
  port: 8083

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_id

redis:
  host: localhost
  port: 6379
  password: ""

auth:
  jwt_secret: "your_secure_jwt_secret_should_be_long_and_random"
  access_token_duration: 15      # в минутах
  refresh_token_duration: 10080  # в минутах (7 дней)
  password_min_length: 8
  password_hash_cost: 10

file_service:
  base_url: "http://localhost:8082"
  service_id: 2

tvm:
  base_url: "http://localhost:8081"
  service_id: 2
  service_secret: "your_tvm_service_secret"

migrations:
  path: "migrations" 