server:
  port: 8083

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_id

redis:
  host: localhost
  port: 6379
  password: ""

auth:
  host: localhost
  port: 8084
  update_interval: 120

file_service:
  base_url: http://localhost:8082
  service_id: 2

tvm:
  base_url: http://localhost:8081
  service_id: 2
  service_secret: secret

migrations:
  path: migrations 