server:
  port: 8083

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_id

redis:
  host: localhost
  port: 6379
  password: ""

auth:
  host: http://localhost
  port: 8084
  update_interval: 10

file_service:
  base_url: http://localhost:8082
  service_id: 2

tvm:
  base_url: http://localhost:8081
  service_id: 2
  service_secret: "/OdF44bzQKMBZOLk+3p8NCR+7MCw8Vafr4Y9uzhMQwaqmLyyVdy0p/ajOk7i1WCv9iYb32SRsObZJu0Oo/FhMw=="

migrations:
  path: migrations

logger:
  level: info 