version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/ff_tvm?sslmode=disable
      - PORT=8080
      - ENVIRONMENT=development
    volumes:
      - ./migrations:/app/migrations

volumes:
  postgres_data: 