// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd3W4bR7J+lcHkXNIWfZJzEOhOjuKFFhvEiGXshS0oY7IlTUzOMDNDrRlDgCVZmwQ2",
	"4uwiCwfBJl4nL0AxZkzLIvUK3W+0qOr55XTPDznin3mTiDSnu7q7vqqvqmu6H6oVs94wDWI4trr6ULUr",
	"e6Su4Z9rFUff153WX3Tb+YzYDdOwCXzfsMwGsRyd4K80/iv3k+6QOv7xPxbZUVfV91aC5lfctle8hv1G",
	"D0qq02oQdVXVLEtrqQfBF+a9L0jFgV8ET33ZJLYTl6RK7IqlNxzdNGIfVfoLvaA9dkjbtE97tKvQNj1j",
	"R7RHO7RPB+wQ/lb9bm3H0o1d6FavmMa2Xo23uLGu0B49owPap2fhZ3XDIbvEgoebNrGED9N/0j47Zkfs",
	"Ee3SPor0RoEWL+iAvmVP6Ws6oB3aZke0S9+yZ2pJ3TGtuubw9v//A0F3ByXVIl82dYtU1dU7kQ63Eucz",
	"ZWlb0uEnTmFoGqqaQxy9TgTz8AOOsa3QnkI7OBvn7JmsZX8KoMEr2KJgxWZOD4TaXK3etollS7XZVR1b",
	"MISX7hAG9EyuM7RL3yj0FSgP/G9AT2mbdvD7Pu2hRvlgTVUtAT7DqubLKtKzjzSH7JpWihmp8F/lMSNe",
	"w/nMSPCUZOLHAryhCbX8Z9qmr2FtPKU7c5fpdzpgj2hPpHJDc4wtB2q4lTg02SzD02nTulExjfXNT1Hn",
	"JbOQIP2lzYV0tJv4D7FufqU9eiFunBjNOkwp2SeGA51ZmmGDsYtYygD66+SeAzMSN5B1s2k4gs7/g2M8",
	"p132iIPvLf2dtiMWzGzeq4XMl9Gs3+PTtmOZ9e38joP38gd+cxbtS45q2QKHRRbYAnME+c7wm1e0x45w",
	"KTJKGFobGSixM9Cm12jL/y5RSJEOwcom26UquedkN0mepmSyROvNer0FTkBqigy9cl+KIljmPlh5eq5U",
	"oakrCeQhxbZ4/YisyseWZVryCSLwz2nzEmljnTiaXktSP1jIC/YI3HFYBSXS61XANIqRKv9atapDR1pt",
	"XXO0+GjsWnNXyFIGfHLRd/JpfUr7tA3OtUf77DHq9Dltg/rhjJMHWr1RQ7GhzUwmTTRNcU9pVkUK8RMd",
	"0FcKHbBvaI+eug4qEGJfq+lVDX8sokzuZGRew6F5PCipdWLb2i4R0pUB0A/2LaceYPIH9DQsajciqm6g",
	"sIpuNJpO6urjdATdCzUA7HwyzNEVZMc5tpiPd+AjnxCw8rbQmQCGdWJvAxDTWB/tgXOh/UTgg20Is7zY",
	"qkeFLhVCOcelleJ5k1pIlzbKQ5RsVCVnyICOHUwCNMmeQcggsrKglbjemdQppBs5yFNGUURkcks+2zKY",
	"3NNqmlERCfYP2qZvQSx2mCpUaOJnfP1kUskayKDxBS9sSW3smY4pnL/bt4EdgWs6ooNsHsgj/3ED+cAh",
	"lqHVtptNGe2jXfaNS/igZ5GsO3qNSFrwhG3TN6BIklArfWmKitASu5dNndROFTjwogYgCC4DKUW24dOG",
	"o9f1r0h1svEQuubtS0DiLARaIPgRevMefU17OBS+hn06AKM3O7HYQZpKJDMs0/vpdr6QKqZ1mVjDrT3N",
	"IkIdTQ55e5cchE44JVwC3t8k2RDZy4JH4WQ3KxVi2/K1t/kPRLySHcGI2DE7VOA/9IJ22QlYwQH++YhH",
	"VOG5vGeaNaIZMRvmdSIyXbdaRmVy6VZ2iDHhCaK5j8gORjGZpOumZt8Xqn/FIppDqtuak5CMx8G+pq+4",
	"M4mqWpGpd8DKK9pmX4s93aVZ/qS8Q0ye0HMNSzct3WkJxvYC2SlyVFAIdpTemqM7NRE0n9M2WH76FvUL",
	"w72UiZr0NpNQ3ZLNv6PZ97MbfU99M9l6+HFRm4IpE71UgPg+Ix9FIMOWdImSdCOzRgg1IPDPKVoY/DCH",
	"MgYP5Uv5RB6U6KeUMv+CGbM2uhN2TM/pORhmMcvIs6swvo6UICofcOrInoDbw3wtBC/IZd8WGggnE6sQ",
	"NE3LA7nmJydvRoOw9GmKsyTgJC5d7nq7p2ApOGfiGa/YyocJY/4UR3Yy6STtfSF5EkjP09PuHliDWBW+",
	"C+ZqYkltGrpjCzfCQH/GYkhX2DH7GqRiR278NKCdIkmRG8j6YwnU3n3QG8RWGl6lRREywL4sAKW5CyVS",
	"u0pma24gJtjtgIgzQldH2vaaRPSey6C99c3YU/ZtAQF8ZqQWbO1siG/la9fLmKFPWlQ/hBas6uzbtwwJ",
	"OwgIk+mCb+8yTRi0d9Myd/Qaycxdh56JZysMN+1aBLlTaAdjUzS/XQDfWJ76R16qlXnTuZR9PztPo5j/",
	"Tkl+52pwytEUoJtUmhBm3ALN4opwnWgWsdaazh7uw+CnG17jf/7rphrjLt/Tjpve8xMQ4DC+RpPbpa8V",
	"3qQCP6JnMCK1xMs/McuC/xgIvOc4DfUAhNONHZPvQxuOVkFPyNdUvaEbN2rm35RNotXjZGrt5kYoQQJC",
	"dHjspbBjBHGkPI3nIDroIZAtsCf0HEwHgp6d0AGmJ87RHSpuz1fvGncN+jJoXPGtA6/swy7YMwzP2GN2",
	"TPuu+RnQPm27m/r4U/bUFXb1rnFFob8JJBR7Ly5Sj8t/yp4E32JDL6OZFXTnA3bEDrHhP7AO0fs3gZl8",
	"g43w5F3E5EUnZkA7KB79g75ix1IF9aUSDi+IOdveoOLFkqFGQKpTHMwTBaZ+yO4HUxPammjzp+8a772n",
	"0O8BXNA/ztlj7p653uLCPqdtcNpuIQFoRFchRrVh6oZjKy4uT9kx+w6i77asNVicBBSs3jU+//zzuwZg",
	"zbT0r7BoYtX73d1mufx+RcNU47Zj3icGfkPch9SSWtMrxPUmLi4+2dgMhfs+TG41arqj3CLWvl4hytrN",
	"DbWk7hPL5nC5drV8tQyPmQ1iaA1dXVXfv1q++r5aUhuas4dGYUVr6Cv711Y8Fwzf7RJHaLlA7TqoJN/S",
	"NgfAYbiioIOgPIm76zeAzzPUuPC+BKrBBdIncFg4SxtVdVX9E3E+Coo5QVpLqxMHPemdPGV6Ovzgyyax",
	"Wqrng4L9YpfMB9zfsZrEtV9a1spRLB08ONiCdjgHwGn933LZM3CEU32t0ajpFRzjyhc2jzLzdRUhGmhH",
	"k8o7YmsAivB/BYoVLeoSyTPk69gzMAlByU47MOKYped+q1mva6CGKn2BFgeivR4a06iyxcdXUh1t18aC",
	"nkB5tqDRYSVfeahXD/JpuqBE6zsFWEGcmoKpRJ/eczWcHSdoeOt6Cze6E3VcVsaA+g1YDtQbS9nkOh0n",
	"D+8snhJ198d4RZ54uQFWH5Q/mCCsfhp2igqQXgXpxxt06X0A05yjPeb7v8sAcF6OXYQLExAzNDExGH/M",
	"y/4uUV/jtYepxl8s/WI5ANkKeTri1mNuYWLXdiRVpZxIo4Xvu3sl4sopjHSjq/8RboR+7L4CYPH8/HWz",
	"2ip26b3E/0E0UwnW9SCmdteK7jthef8tmqXozu+Am8dJKt3PtIubC49Q7c7cwA/T7W2f8w/Vh88bMnzN",
	"5aZSpq4xKAybSiBC2/jXAcdHjTii1MpvOHle2Cvuz+M9MZisY6seTIZ4jpDBbJMQpsRcIj0rcpkUYrhc",
	"JQc6jvlU4roPJk8exFLFCcRg7jDh6qhHHzJjolREFCDqrSdFhEcbxNR/PiGR7i5klFo4d0tkXCK1zoGN",
	"RlNSWeDSJd8n5EJGDBG3G1VtWj5iFmhbeeq0DV/vdtc07JzmgLot7UQxdiJAda84XrniHQExTlgeP2AB",
	"a2Vle/8xb7vmnzByvYUAWRy/KzxiJTVBIJzQ+XdsgoM4El6DcrU4dPxMzmQBOwYnF9/Qeqq4m2cZPB9P",
	"IniruADOb/iQnQmnLeInAwn07nvBkkXyFu1l3mICeQsBcmS4zOJh8DvvQ66EhlgQURpjGkAtyRrXAmFy",
	"7PhMOzEiBF84LTIFUieSaRF2VYaSIjkAV0BahJ7KjsaSEbTWpDMicwStTI5NnGORLcQSZhMjoklAGzPH",
	"khVmPMeyKA5sRohrefrENZa5aS8zN++U9YnlbQri1f7LHaOmbbxzBwaScFicrFmHbhcuTxM73iA1RxOa",
	"vfl3iN5gMuRjIm9YJmuofyLElRF0NenkDM94pQod097IYROLp8by4zpS9TlxutnJgil8duWSq740Gfkc",
	"HekxO8SqaoEy++xwBBPsLTEq8Luptz8EwJeuI3syh0RBOJYhCz2aKfbewB+VK/iviuSwtZuafX/xTGzs",
	"JIxUy+rP3fybzdApFRmYAp4IMtKmjd8PO869WQMLtAAbNeFDTya8SRM5zEOkVs+DF8eWGzOT35gJoUMA",
	"tzQ3gJ/hj1x7MNE+RXsvk8adNG3lcEHmaM8lgqcp77WEZVnAPZZk7BRSbRo4ya6MFs3MRspsYSXV8ciK",
	"VMNTvkTMpbE+CWbGrkJNQgzfF5l35zID/LA8HX643P94R81IbN9jDNoaur9n9CSG6LSNPOmMULZl8bIa",
	"kgMW05Ibojmd/zdZBadX5d4YyZ/1iHcL7jFv9iMElQVIgsQP2Jx0LkR0NqhABX+Nrd2zZWpk4qkREYRG",
	"TJgHP+UJk+BznryJRCBh/mQ6yJUz3Yg8c5RNEUJxylkVkUyLl13JB78iki2SgyaTyNvs5F5mEWBZ/Z0k",
	"EyNcjyXaJkZUk/E2bqImE9rchM1CebPZYbblmWC2y6TOO26JhpM7xRFv78TvUStVEi7vyZzqwZuEFi7H",
	"EzsOO7VyRX7E+NzvaYygJp4yu/cLyDM8PwSX8XsONaG7TtYDzdaqVVTMTXNRTuLwRjQlD5glmHwhXLge",
	"L8g7DU5U5vWGy/xO0cANsJQO3E76mRgedtM80Ip7WfMYnijt5uY871xwYZYeKfU27Hn3Sxmu+x5JldFm",
	"Z9qQSJKA3zCRaz8CVLd1m9/PM+/uyh/LlPYihu8fiavjetLiRQ/RWLqry9+OSMbSKFiGz/BHrtpNKZZ7",
	"9HVWL/QZqZv7BDTwhmXWJ05ApXkd9+qveT6K9IUMraE9i8lnLmRSxbIX814ROho6RkfuBF+LHN+JC16Z",
	"BBswIzsoMw7+5duYhb+NqWRwpvJkY10ztF0SuU0n96tJsYsPct6ew2mxd8vF/FyfUzydDm76mAqbznTR",
	"SPw2j2VRz8TfdxrlrpEhqPt3CmXlzOPCnNf0ZIX58gahCXNuAa6nXCG0mPcGDXHtzEgu4KUSwa20uRDM",
	"6xiWCJ4DUlCeNilY1kO801Yu9qrLGIxFr0DYUsQlad4lrAN6JorrN7CjMbGU6d5s6El8YXZKFBwewWJd",
	"jxZdG081+NqPdGKGf+Ou4P18HnLCKlzSRWjQ9JSiOF+3hDWq/i3Ey7Bt8mFbVCWHdVxi+XIHakmKz4Mw",
	"V/GzpCvn60WHiH5POXwJy7KAgUuyLhd0Gndwa3o36XIy0OccLzHMjk4n22rZ0dihWVmqdeGp9zTFLuD0",
	"6/ACioPsy7XQM8B3yhPnO8uI9B1FeCwWzUzDcJuaPHCIZWi1nLvSnajQeOnaxnpitSY4OD8oOsOD/mD+",
	"2TfwODtRNtavKvRf7JCX215kLUdQaAea7bnXZp3Tbgk/0z47wY3FvrfJyI657F2eBzxUdnau6NVgenmw",
	"dp70goA7WRvrdupGXiSwHR6pkljxRx40amaVqKs7Ws0m4hxfU6/aibbRj9RT98SHo/SSajutGnwBj6rz",
	"8o4CrKhAL89Bm3qRJcDvNtaXQeFEGMeIpiK6YJwaJxThoDEDlQZ8RsvmCjjijS/HY9oDCZNqEoSWI88b",
	"yDNe4pJekio9s02y3stKt8t86ynQ24TStwzIsltGJbF8JsHfSkElload5PDNt1pGBZ3zJWU6/fbn8JUl",
	"MQuKHpi+9H/FJ0Wlk57yQpMIhtA2qTQtvLH3zkP1OtEsYq01nT119c4WmHqbWPtiCrpO9knNbNSJ4Sj8",
	"V2pJbVo1dVXdc5zG6spKzaxotT3TdlY/LH94DZmeK4EgC3uBb/x64SXesiwslgV2Fbg091Jiwaa2qEXB",
	"a8VD7UWK/TK2KrM0nBuKCmPfhIg2LkXWnuJ3/QzJH7ruJ2ubwWmZ7aG5wKP0sjYzvEc5JFhomzJri0Gi",
	"Z0gwHmwebB38NwAA//8zHil9jb4AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
