server:
  port: 8082

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_files

minio:
  endpoint: localhost:9000
  access_key: minioadmin
  secret_key: minioadmin
  bucket: ff-files
  use_ssl: false
  root_user: minioadmin
  root_password: minioadmin
  file_time_expiration: 300

redis:
  host: localhost
  port: 6379
  password: ""

tvm:
  base_url: http://localhost:8081
  service_id: 1
  service_secret: secret

migrations:
  path: migrations 