server:
  port: 8084

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: ff_id

auth:
  jwt_secret: "super_secret_key_change_in_production"
  access_token_duration: 15
  refresh_token_duration: 10080
  password_min_length: 8
  password_hash_cost: 10

tvm:
  base_url: http://localhost:8081
  service_id: 2
  service_secret: secret

migrations:
  path: migrations 