server:
  port: ":8081"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "ff_id"

jwt:
  signing_key: "your-secret-key-here"
  expiration: "24h"

services:
  tvm_url: "http://ff-tvm:8083"
  files_url: "http://ff-files:8082" 