// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/activity.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ivasnev/FinFlow/ff-split/internal/models"
)

// MockActivity is a mock of Activity interface.
type MockActivity struct {
	ctrl     *gomock.Controller
	recorder *MockActivityMockRecorder
}

// MockActivityMockRecorder is the mock recorder for MockActivity.
type MockActivityMockRecorder struct {
	mock *MockActivity
}

// NewMockActivity creates a new mock instance.
func NewMockActivity(ctrl *gomock.Controller) *MockActivity {
	mock := &MockActivity{ctrl: ctrl}
	mock.recorder = &MockActivityMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivity) EXPECT() *MockActivityMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockActivity) Create(ctx context.Context, activity *models.Activity) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, activity)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockActivityMockRecorder) Create(ctx, activity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockActivity)(nil).Create), ctx, activity)
}

// Delete mocks base method.
func (m *MockActivity) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockActivityMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockActivity)(nil).Delete), ctx, id)
}

// GetByEventID mocks base method.
func (m *MockActivity) GetByEventID(ctx context.Context, eventID int64) ([]models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventID", ctx, eventID)
	ret0, _ := ret[0].([]models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventID indicates an expected call of GetByEventID.
func (mr *MockActivityMockRecorder) GetByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventID", reflect.TypeOf((*MockActivity)(nil).GetByEventID), ctx, eventID)
}

// GetByID mocks base method.
func (m *MockActivity) GetByID(ctx context.Context, id int) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockActivityMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockActivity)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockActivity) Update(ctx context.Context, id int, activity *models.Activity) (*models.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, activity)
	ret0, _ := ret[0].(*models.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockActivityMockRecorder) Update(ctx, id, activity interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockActivity)(nil).Update), ctx, id, activity)
}
