// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/icon.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ivasnev/FinFlow/ff-split/internal/models"
)

// MockIcon is a mock of Icon interface.
type MockIcon struct {
	ctrl     *gomock.Controller
	recorder *MockIconMockRecorder
}

// MockIconMockRecorder is the mock recorder for MockIcon.
type MockIconMockRecorder struct {
	mock *MockIcon
}

// NewMockIcon creates a new mock instance.
func NewMockIcon(ctrl *gomock.Controller) *MockIcon {
	mock := &MockIcon{ctrl: ctrl}
	mock.recorder = &MockIconMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIcon) EXPECT() *MockIconMockRecorder {
	return m.recorder
}

// CreateIcon mocks base method.
func (m *MockIcon) CreateIcon(icon *models.Icon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIcon", icon)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIcon indicates an expected call of CreateIcon.
func (mr *MockIconMockRecorder) CreateIcon(icon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIcon", reflect.TypeOf((*MockIcon)(nil).CreateIcon), icon)
}

// DeleteIcon mocks base method.
func (m *MockIcon) DeleteIcon(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIcon", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIcon indicates an expected call of DeleteIcon.
func (mr *MockIconMockRecorder) DeleteIcon(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIcon", reflect.TypeOf((*MockIcon)(nil).DeleteIcon), id)
}

// GetIconByID mocks base method.
func (m *MockIcon) GetIconByID(id uint) (*models.Icon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIconByID", id)
	ret0, _ := ret[0].(*models.Icon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIconByID indicates an expected call of GetIconByID.
func (mr *MockIconMockRecorder) GetIconByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIconByID", reflect.TypeOf((*MockIcon)(nil).GetIconByID), id)
}

// GetIcons mocks base method.
func (m *MockIcon) GetIcons() ([]models.Icon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIcons")
	ret0, _ := ret[0].([]models.Icon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIcons indicates an expected call of GetIcons.
func (mr *MockIconMockRecorder) GetIcons() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIcons", reflect.TypeOf((*MockIcon)(nil).GetIcons))
}

// UpdateIcon mocks base method.
func (m *MockIcon) UpdateIcon(icon *models.Icon) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateIcon", icon)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateIcon indicates an expected call of UpdateIcon.
func (mr *MockIconMockRecorder) UpdateIcon(icon interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateIcon", reflect.TypeOf((*MockIcon)(nil).UpdateIcon), icon)
}
