// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/transaction.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ivasnev/FinFlow/ff-split/internal/models"
)

// MockTransaction is a mock of Transaction interface.
type MockTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionMockRecorder
}

// MockTransactionMockRecorder is the mock recorder for MockTransaction.
type MockTransactionMockRecorder struct {
	mock *MockTransaction
}

// NewMockTransaction creates a new mock instance.
func NewMockTransaction(ctrl *gomock.Controller) *MockTransaction {
	mock := &MockTransaction{ctrl: ctrl}
	mock.recorder = &MockTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransaction) EXPECT() *MockTransactionMockRecorder {
	return m.recorder
}

// CreateDebts mocks base method.
func (m *MockTransaction) CreateDebts(debts []models.Debt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDebts", debts)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDebts indicates an expected call of CreateDebts.
func (mr *MockTransactionMockRecorder) CreateDebts(debts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDebts", reflect.TypeOf((*MockTransaction)(nil).CreateDebts), debts)
}

// CreateTransaction mocks base method.
func (m *MockTransaction) CreateTransaction(tx *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransaction indicates an expected call of CreateTransaction.
func (mr *MockTransactionMockRecorder) CreateTransaction(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransaction", reflect.TypeOf((*MockTransaction)(nil).CreateTransaction), tx)
}

// CreateTransactionShares mocks base method.
func (m *MockTransaction) CreateTransactionShares(shares []models.TransactionShare) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransactionShares", shares)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTransactionShares indicates an expected call of CreateTransactionShares.
func (mr *MockTransactionMockRecorder) CreateTransactionShares(shares interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransactionShares", reflect.TypeOf((*MockTransaction)(nil).CreateTransactionShares), shares)
}

// DeleteDebtsByTransactionID mocks base method.
func (m *MockTransaction) DeleteDebtsByTransactionID(transactionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDebtsByTransactionID", transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDebtsByTransactionID indicates an expected call of DeleteDebtsByTransactionID.
func (mr *MockTransactionMockRecorder) DeleteDebtsByTransactionID(transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDebtsByTransactionID", reflect.TypeOf((*MockTransaction)(nil).DeleteDebtsByTransactionID), transactionID)
}

// DeleteOptimizedDebtsByEventID mocks base method.
func (m *MockTransaction) DeleteOptimizedDebtsByEventID(eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOptimizedDebtsByEventID", eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOptimizedDebtsByEventID indicates an expected call of DeleteOptimizedDebtsByEventID.
func (mr *MockTransactionMockRecorder) DeleteOptimizedDebtsByEventID(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOptimizedDebtsByEventID", reflect.TypeOf((*MockTransaction)(nil).DeleteOptimizedDebtsByEventID), eventID)
}

// DeleteSharesByTransactionID mocks base method.
func (m *MockTransaction) DeleteSharesByTransactionID(transactionID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSharesByTransactionID", transactionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSharesByTransactionID indicates an expected call of DeleteSharesByTransactionID.
func (mr *MockTransactionMockRecorder) DeleteSharesByTransactionID(transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSharesByTransactionID", reflect.TypeOf((*MockTransaction)(nil).DeleteSharesByTransactionID), transactionID)
}

// DeleteTransaction mocks base method.
func (m *MockTransaction) DeleteTransaction(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTransaction", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTransaction indicates an expected call of DeleteTransaction.
func (mr *MockTransactionMockRecorder) DeleteTransaction(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTransaction", reflect.TypeOf((*MockTransaction)(nil).DeleteTransaction), id)
}

// GetDebtsByEventID mocks base method.
func (m *MockTransaction) GetDebtsByEventID(eventID int64) ([]models.Debt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebtsByEventID", eventID)
	ret0, _ := ret[0].([]models.Debt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDebtsByEventID indicates an expected call of GetDebtsByEventID.
func (mr *MockTransactionMockRecorder) GetDebtsByEventID(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebtsByEventID", reflect.TypeOf((*MockTransaction)(nil).GetDebtsByEventID), eventID)
}

// GetDebtsByEventIDFromUser mocks base method.
func (m *MockTransaction) GetDebtsByEventIDFromUser(eventID, userID int64) ([]models.Debt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebtsByEventIDFromUser", eventID, userID)
	ret0, _ := ret[0].([]models.Debt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDebtsByEventIDFromUser indicates an expected call of GetDebtsByEventIDFromUser.
func (mr *MockTransactionMockRecorder) GetDebtsByEventIDFromUser(eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebtsByEventIDFromUser", reflect.TypeOf((*MockTransaction)(nil).GetDebtsByEventIDFromUser), eventID, userID)
}

// GetDebtsByEventIDToUser mocks base method.
func (m *MockTransaction) GetDebtsByEventIDToUser(eventID, userID int64) ([]models.Debt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebtsByEventIDToUser", eventID, userID)
	ret0, _ := ret[0].([]models.Debt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDebtsByEventIDToUser indicates an expected call of GetDebtsByEventIDToUser.
func (mr *MockTransactionMockRecorder) GetDebtsByEventIDToUser(eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebtsByEventIDToUser", reflect.TypeOf((*MockTransaction)(nil).GetDebtsByEventIDToUser), eventID, userID)
}

// GetDebtsByTransactionID mocks base method.
func (m *MockTransaction) GetDebtsByTransactionID(transactionID int) ([]models.Debt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDebtsByTransactionID", transactionID)
	ret0, _ := ret[0].([]models.Debt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDebtsByTransactionID indicates an expected call of GetDebtsByTransactionID.
func (mr *MockTransactionMockRecorder) GetDebtsByTransactionID(transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDebtsByTransactionID", reflect.TypeOf((*MockTransaction)(nil).GetDebtsByTransactionID), transactionID)
}

// GetOptimizedDebtsByEventID mocks base method.
func (m *MockTransaction) GetOptimizedDebtsByEventID(eventID int64) ([]models.OptimizedDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptimizedDebtsByEventID", eventID)
	ret0, _ := ret[0].([]models.OptimizedDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptimizedDebtsByEventID indicates an expected call of GetOptimizedDebtsByEventID.
func (mr *MockTransactionMockRecorder) GetOptimizedDebtsByEventID(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptimizedDebtsByEventID", reflect.TypeOf((*MockTransaction)(nil).GetOptimizedDebtsByEventID), eventID)
}

// GetOptimizedDebtsByEventIDWithUsers mocks base method.
func (m *MockTransaction) GetOptimizedDebtsByEventIDWithUsers(eventID int64) ([]models.OptimizedDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptimizedDebtsByEventIDWithUsers", eventID)
	ret0, _ := ret[0].([]models.OptimizedDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptimizedDebtsByEventIDWithUsers indicates an expected call of GetOptimizedDebtsByEventIDWithUsers.
func (mr *MockTransactionMockRecorder) GetOptimizedDebtsByEventIDWithUsers(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptimizedDebtsByEventIDWithUsers", reflect.TypeOf((*MockTransaction)(nil).GetOptimizedDebtsByEventIDWithUsers), eventID)
}

// GetOptimizedDebtsByUserID mocks base method.
func (m *MockTransaction) GetOptimizedDebtsByUserID(eventID, userID int64) ([]models.OptimizedDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptimizedDebtsByUserID", eventID, userID)
	ret0, _ := ret[0].([]models.OptimizedDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptimizedDebtsByUserID indicates an expected call of GetOptimizedDebtsByUserID.
func (mr *MockTransactionMockRecorder) GetOptimizedDebtsByUserID(eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptimizedDebtsByUserID", reflect.TypeOf((*MockTransaction)(nil).GetOptimizedDebtsByUserID), eventID, userID)
}

// GetOptimizedDebtsByUserIDWithUsers mocks base method.
func (m *MockTransaction) GetOptimizedDebtsByUserIDWithUsers(eventID, userID int64) ([]models.OptimizedDebt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOptimizedDebtsByUserIDWithUsers", eventID, userID)
	ret0, _ := ret[0].([]models.OptimizedDebt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOptimizedDebtsByUserIDWithUsers indicates an expected call of GetOptimizedDebtsByUserIDWithUsers.
func (mr *MockTransactionMockRecorder) GetOptimizedDebtsByUserIDWithUsers(eventID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOptimizedDebtsByUserIDWithUsers", reflect.TypeOf((*MockTransaction)(nil).GetOptimizedDebtsByUserIDWithUsers), eventID, userID)
}

// GetSharesByTransactionID mocks base method.
func (m *MockTransaction) GetSharesByTransactionID(transactionID int) ([]models.TransactionShare, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharesByTransactionID", transactionID)
	ret0, _ := ret[0].([]models.TransactionShare)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSharesByTransactionID indicates an expected call of GetSharesByTransactionID.
func (mr *MockTransactionMockRecorder) GetSharesByTransactionID(transactionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharesByTransactionID", reflect.TypeOf((*MockTransaction)(nil).GetSharesByTransactionID), transactionID)
}

// GetTransactionByID mocks base method.
func (m *MockTransaction) GetTransactionByID(id int) (*models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionByID", id)
	ret0, _ := ret[0].(*models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionByID indicates an expected call of GetTransactionByID.
func (mr *MockTransactionMockRecorder) GetTransactionByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionByID", reflect.TypeOf((*MockTransaction)(nil).GetTransactionByID), id)
}

// GetTransactionsByEventID mocks base method.
func (m *MockTransaction) GetTransactionsByEventID(eventID int64) ([]models.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionsByEventID", eventID)
	ret0, _ := ret[0].([]models.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionsByEventID indicates an expected call of GetTransactionsByEventID.
func (mr *MockTransactionMockRecorder) GetTransactionsByEventID(eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionsByEventID", reflect.TypeOf((*MockTransaction)(nil).GetTransactionsByEventID), eventID)
}

// SaveOptimizedDebts mocks base method.
func (m *MockTransaction) SaveOptimizedDebts(eventID int64, debts []models.OptimizedDebt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveOptimizedDebts", eventID, debts)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveOptimizedDebts indicates an expected call of SaveOptimizedDebts.
func (mr *MockTransactionMockRecorder) SaveOptimizedDebts(eventID, debts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveOptimizedDebts", reflect.TypeOf((*MockTransaction)(nil).SaveOptimizedDebts), eventID, debts)
}

// UpdateTransaction mocks base method.
func (m *MockTransaction) UpdateTransaction(tx *models.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransaction", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransaction indicates an expected call of UpdateTransaction.
func (mr *MockTransactionMockRecorder) UpdateTransaction(tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransaction", reflect.TypeOf((*MockTransaction)(nil).UpdateTransaction), tx)
}
