// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ivasnev/FinFlow/ff-split/internal/models"
)

// MockUser is a mock of User interface.
type MockUser struct {
	ctrl     *gomock.Controller
	recorder *MockUserMockRecorder
}

// MockUserMockRecorder is the mock recorder for MockUser.
type MockUserMockRecorder struct {
	mock *MockUser
}

// NewMockUser creates a new mock instance.
func NewMockUser(ctrl *gomock.Controller) *MockUser {
	mock := &MockUser{ctrl: ctrl}
	mock.recorder = &MockUserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUser) EXPECT() *MockUserMockRecorder {
	return m.recorder
}

// AddUserToEvent mocks base method.
func (m *MockUser) AddUserToEvent(ctx context.Context, userID, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserToEvent indicates an expected call of AddUserToEvent.
func (mr *MockUserMockRecorder) AddUserToEvent(ctx, userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToEvent", reflect.TypeOf((*MockUser)(nil).AddUserToEvent), ctx, userID, eventID)
}

// AddUsersToEvent mocks base method.
func (m *MockUser) AddUsersToEvent(ctx context.Context, ids []int64, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUsersToEvent", ctx, ids, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUsersToEvent indicates an expected call of AddUsersToEvent.
func (mr *MockUserMockRecorder) AddUsersToEvent(ctx, ids, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUsersToEvent", reflect.TypeOf((*MockUser)(nil).AddUsersToEvent), ctx, ids, eventID)
}

// BatchCreate mocks base method.
func (m *MockUser) BatchCreate(ctx context.Context, users []*models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockUserMockRecorder) BatchCreate(ctx, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockUser)(nil).BatchCreate), ctx, users)
}

// BatchCreateOrUpdate mocks base method.
func (m *MockUser) BatchCreateOrUpdate(ctx context.Context, users []*models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreateOrUpdate", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreateOrUpdate indicates an expected call of BatchCreateOrUpdate.
func (mr *MockUserMockRecorder) BatchCreateOrUpdate(ctx, users interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreateOrUpdate", reflect.TypeOf((*MockUser)(nil).BatchCreateOrUpdate), ctx, users)
}

// Create mocks base method.
func (m *MockUser) Create(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserMockRecorder) Create(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUser)(nil).Create), ctx, user)
}

// CreateOrUpdate mocks base method.
func (m *MockUser) CreateOrUpdate(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdate", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdate indicates an expected call of CreateOrUpdate.
func (mr *MockUserMockRecorder) CreateOrUpdate(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdate", reflect.TypeOf((*MockUser)(nil).CreateOrUpdate), ctx, user)
}

// Delete mocks base method.
func (m *MockUser) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUser)(nil).Delete), ctx, id)
}

// GetByEventID mocks base method.
func (m *MockUser) GetByEventID(ctx context.Context, eventID int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEventID", ctx, eventID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEventID indicates an expected call of GetByEventID.
func (mr *MockUserMockRecorder) GetByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEventID", reflect.TypeOf((*MockUser)(nil).GetByEventID), ctx, eventID)
}

// GetByExternalUserID mocks base method.
func (m *MockUser) GetByExternalUserID(ctx context.Context, userID int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalUserID", ctx, userID)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalUserID indicates an expected call of GetByExternalUserID.
func (mr *MockUserMockRecorder) GetByExternalUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalUserID", reflect.TypeOf((*MockUser)(nil).GetByExternalUserID), ctx, userID)
}

// GetByExternalUserIDs mocks base method.
func (m *MockUser) GetByExternalUserIDs(ctx context.Context, ids []int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByExternalUserIDs", ctx, ids)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByExternalUserIDs indicates an expected call of GetByExternalUserIDs.
func (mr *MockUserMockRecorder) GetByExternalUserIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByExternalUserIDs", reflect.TypeOf((*MockUser)(nil).GetByExternalUserIDs), ctx, ids)
}

// GetByInternalUserID mocks base method.
func (m *MockUser) GetByInternalUserID(ctx context.Context, id int64) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInternalUserID", ctx, id)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInternalUserID indicates an expected call of GetByInternalUserID.
func (mr *MockUserMockRecorder) GetByInternalUserID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInternalUserID", reflect.TypeOf((*MockUser)(nil).GetByInternalUserID), ctx, id)
}

// GetByInternalUserIDs mocks base method.
func (m *MockUser) GetByInternalUserIDs(ctx context.Context, ids []int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByInternalUserIDs", ctx, ids)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByInternalUserIDs indicates an expected call of GetByInternalUserIDs.
func (mr *MockUserMockRecorder) GetByInternalUserIDs(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByInternalUserIDs", reflect.TypeOf((*MockUser)(nil).GetByInternalUserIDs), ctx, ids)
}

// GetDummiesByEventID mocks base method.
func (m *MockUser) GetDummiesByEventID(ctx context.Context, eventID int64) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDummiesByEventID", ctx, eventID)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDummiesByEventID indicates an expected call of GetDummiesByEventID.
func (mr *MockUserMockRecorder) GetDummiesByEventID(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDummiesByEventID", reflect.TypeOf((*MockUser)(nil).GetDummiesByEventID), ctx, eventID)
}

// RemoveUserFromEvent mocks base method.
func (m *MockUser) RemoveUserFromEvent(ctx context.Context, userID, eventID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserFromEvent", ctx, userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveUserFromEvent indicates an expected call of RemoveUserFromEvent.
func (mr *MockUserMockRecorder) RemoveUserFromEvent(ctx, userID, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserFromEvent", reflect.TypeOf((*MockUser)(nil).RemoveUserFromEvent), ctx, userID, eventID)
}

// Update mocks base method.
func (m *MockUser) Update(ctx context.Context, user *models.User) (*models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(*models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserMockRecorder) Update(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUser)(nil).Update), ctx, user)
}
